### ISSUE TITLE
Display council members

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#1385]
@[figma](https://www.figma.com/file/Z3KcRoAll3JGEY622o0iZu/Council?node-id=220%3A22645)

Display a list of council members

- [x] Fetch council members from the query-node
- Handle fields
  - [x] Member info
  - [x] Own reward
  - [x] Voters stake
  - [x] Elected times count
- [x] Click on the council member row opens member details
- [x] Allow sorting by the above
- [x] Handle empty state

**Comment by thesan** [comment]
@jodator what comes to my mind now is the various common errors which can happen when mocking data, eg:
- `Mirage: The xxx model has multiple possible inverse associations for the xxx.xxx association.`
- The error when an object is passed as an attribute in the seeding process instead of creating a model...
- Or even, no resolver being found when q new query hasn't been added to the Mirage server

**Comment by thesan** [comment]
@jodator is the second field the "Owed reward" which would be the `CouncilMember.unpaidReward` from schema? I haven't found anything about a "Own" reward in the handbook

**Comment by jodator** [comment]
> @jodator is the second field the "Owed reward" which would be the `CouncilMember.unpaidReward` from schema?

I think yes. It might be a typo. IMO it should be "owed" as unpaid [reward](https://joystream.gitbook.io/joystream-handbook/governance/council#rewards).
