### ISSUE TITLE
Proposals tracking issue

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#1802]
This is a tracking issue of proposals done and to be implemented on "Add new proposal" modal.

### Proposals to implement:

*   [x] #1807
*   [x] #1809
*   [x] #1821
*   [x] #1826
*   [x] #1854
*   [x] #1857
*   [x] #1861
*   [x] #1829
*   [x] #1830
*   [x] #1862
*   [x] #1866
*   [x] #1831
*   [x] #1832

### Additional proposals

Ranked in decreasing value

*   [ ] [Amend Constitution](https://joystream.gitbook.io/joystream-handbook/governance/proposals#amend-constitution) (#876)
*   [x] #1881

### Proposals done:

*   [x] [Decrease Working Group Lead Stake](https://joystream.gitbook.io/joystream-handbook/governance/proposals#decrease-working-group-lead-stake)
*   [x] [Slash Working Group Lead](https://joystream.gitbook.io/joystream-handbook/governance/proposals#slash-working-group-lead)
*   [x] [Funding Request](https://joystream.gitbook.io/joystream-handbook/governance/proposals#funding-request)
*   [x] [Runtime Upgrade](https://joystream.gitbook.io/joystream-handbook/governance/proposals#runtime-upgrade)
*   [x] [Create Working Group Lead Opening](https://joystream.gitbook.io/joystream-handbook/governance/proposals#create-working-group-lead-opening)

Blog related proposals moved to: #1880
