### ISSUE TITLE
Proposal Execution Constraints Validation

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#2242]
credit to @bwhm 

# Background

During proposal creation, the user has to provide a range of parameter values, and they are checked across two set of constraints which are executed at different times, creation and execution constraints. Read more here

https://joystream.gitbook.io/joystream-handbook/governance/proposals#parameters-general-and-specific

Currently, Pioneer does not attempt to assist the user to select inputs that are likely to satisfy execution constraints. This is because a proposal can be created while these constraints are not satisfied, because one leaves the door open that something may change in the interim. However, when this permissiveness on the runtime level is immitated in Pioneer, it leads to a very large share of false positives during proposal creation, because the user is not aware of the full set of constraints that are going to be enforced.

# Proposal

For all proposal creation flows, add checks which warn the user that - if the proposal was executed with the current runtime state, then it would fail. The user should be able to override this warning, if they really know what they are doing, but most people will be very happy to be warned about this. To execute on this, one will have to enumerate the full set of creation constraints for all active proposals, replicate the validation logic in Pioneer, and have some way to indicate such warnings visually.

# Scope
For **all proposal types** listed in this epic as child issues:
- [ ] Check proposal _execution_ constraints (in addition to creation constraints) at the point of proposal creation (proposal specific parameters step)
- [ ] If  exec constraints are violated, show field validation error on each field, displaying the actual constraint values underneath. ⚠️  Execution consttraint of {{constraint_value}} is violated
- [ ] Add Warning info panel ""Parameters provided here are checked across two set of constraints which are executed at different times, creation and execution constraints. Current inputs for proposal parameters violate the execution constraints for this proposal, meaning while you can create this proposal, if the runtime execution constraints for this proposal remain unchanged at the time of council vote, this proposal will be automatically rejected."
[Learn more > ](https://app.gitbook.com/o/-M-C0Rf1ILeSmMugzduG/s/-M-C0W9924TH_Qp2jnDV/governance/proposals#parameters-general-and-specific)"
- [ ] Add checkbox "I understand the implications of overriding the execution constraints validation". Required =true to enable CTA "create proposal".

### Important

ℹ️ To execute on this, one will have to enumerate the full set of creation constraints for all active proposals, replicate the validation logic in Pioneer, and have some way to indicate such warnings visually.

@bwhm seems to have the best expertise and context to help us find/ clarify the execution constraints and this effort is tracked here: #2305

**Comment by dmtrjsg** [comment]
@dmtrjsg to prepare for implementation based on > https://github.com/Joystream/pioneer/issues/2230

**Comment by dmtrjsg** [comment]
Set Working Group Lead Reward even if Lead is not present rn. (As at the point of executioin lead may be in place).

**Comment by traumschule** [comment]
This seems done. Please reopen if you spot missing validations.
