### ISSUE TITLE
Proposal warns - tracking issue

### ISSUE THREAD

**Issue by WRadoslaw** [Joystream/pioneer#2263]
#2242 
Warns to be covered:
---
- [ ]  Funding request  #2321 https://github.com/joystream/pioneer/issues/2321
- The council budget is no less than the sum of `amounts`
---
- [ ] Create Working Group Lead Opening - https://github.com/joystream/pioneer/issues/2280
---

- https://github.com/joystream/pioneer/issues/2323

- [ ] Cancel Working Group Lead Opening
- [ ] Decrease Working Group Lead Stake
- [ ] Terminate Working Group Lead
- Same as when creating an opening for workers in the given group with given inputs, except signer check (?)
---
https://github.com/joystream/pioneer/issues/2324
- [ ] Fill Working Group Lead Opening
- Same as when filling opening in group for worker with given inputs, except application_id as winners and signer check
ℹ️  See details here> https://github.com/Joystream/pioneer/issues/2280

https://github.com/joystream/pioneer/issues/2325
- [ ] Slash working group lead
Same as when slashing a worker in group with given inputs, except
- signer check,
- worker corresponding to worker_id must be lead
---

https://github.com/joystream/pioneer/issues/2326
- [ ] Set Working Group Lead Reward
- Same as when updating reward of a worker in group with given inputs, except signer check
---
https://github.com/joystream/pioneer/issues/2327

- [ ] Update Working Group Budget
- If budget_update is non-negative, then this it must be no less than the council budget, otherwise the absolute value must be no less than the current group budget.
---
https://github.com/joystream/pioneer/issues/2328
- [ ] Set Membership Lead Invitation Quota
- The membership working group has an assigned lead with membership id membership_id.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201854176856314) by [Unito](https://www.unito.io)

**Comment by WRadoslaw** [comment]
@dmtrjsg 

Does that design fulfills the expectations? Ofc message can be adjusted.

![image](https://user-images.githubusercontent.com/92513933/154797424-c54b79fa-f328-44eb-a7d7-0c33767b7d1a.png)

**Comment by bedeho** [comment]
This should not be part of Olympia release, as it is not critical enough to block launch, so removing label.

**Comment by dmtrjsg** [comment]
@WRadoslaw, comments from @MattAugustynowicz 

- Let's replace the icon with an alert from this subpage please, from what I've seen the highlighted messages use outline icons anyway, so we'll remain consistent
Icon 👉 [https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=1405:76570](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=1405%3A76570)
- Let's not use capitals in the word "WARNING". I didn't find this writing structure in the draft, so we'll remain consistent here too. Let's just write "Warning"
- The spacing between the checkbox icon and the text seems to be too large. In the project we have 4px spacing between the 24px icon and the text, so we can use that. But, if you used such checkboxes throughout the project, let's leave it like this 🙂

Copy in the "warning box":
Copy in the "checkbox":

+ Move checkbox to the bottom: like here: 
<img width="743" alt="Screenshot 2022-02-21 at 09 35 18" src="https://user-images.githubusercontent.com/93924525/154927831-752eac63-d9c3-4748-ac4e-7028eb6f05b0.png">

**Comment by dmtrjsg** [comment]
https://github.com/Joystream/pioneer/issues/2305

**Comment by dmtrjsg** [comment]
Closing this issue in favour of tracking each proposal type (with some exceptions for grouping similar ones) as separate issues, mapped to this (original ticket, which is now converted to epic) - #2328

**Comment by dmtrjsg** [comment]
Closing this issue in favour of tracking each proposal type (with some exceptions for grouping similar ones) as separate issues, mapped to this (original ticket, which is now converted to epic) - #2328
