### ISSUE TITLE
Account Locks Info Optimisation

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2300]
## Dev Scope

- [ ] Account locks info on proposal page
- [ ] Flow when no free but some balances
- [ ] Flow when no balances
- [ ] Account Bound to Other Member
- [x] #3043

**Out of scope:**
- [ ] #3042

ℹ️  **Additional Info:**

❓ How to query info about hte lock: [LINK HERE](https://github.com/Joystream/pioneer/issues/1556#issuecomment-963232272)

## Context
Account locks prevent member from participating in some activities. [Concept of rivalrous locks.](https://joystream.gitbook.io/testnet-workspace/system/accounts-and-staking#locks-1)

There are a few opportunities for optimisation:

### 1️⃣ Account recovery notification

Currently there is no way for user to know that, other than just checking the memebrship page. See mechanics of how this is done here[ [loom video]> ](https://www.loom.com/share/14cc5e6f90424e55821b195c8bc8ce98)

### 2️⃣ Account selection for staking purpose
During proposal creation (similar for all cases where stakingis required) It is not clear (especially for users with multiple memebrships) why some accounts are not showing in the drop down and cannot be used. 

Conditions for suitable account to be used for staking:
- No rivalrous locks
- Stake recovered after unlocked for role-based locks; while other locks can be recovered automatically (like proposal locks, when they get rejected)
- Bound to _currently_ selected membership 
#2521  -> this one covers showing the membership on the accounts  with binding locks
- Sufficient balance (> min staking amount)

At the moment we simply hide accounts that are not suitable:
<img width="660" alt="Screenshot 2022-03-09 at 19 17 19" src="https://user-images.githubusercontent.com/93924525/157516711-54195dde-7328-4e8c-9042-6b6d46057ffb.png">

### 3️⃣ Handling situation when no accounts are available, but some might be suitable after funds are transferred
  If there are NO suitable accounts available, rn there's lack of clarity which ones could be used and if at all.

There was a suggestion for improvement:

<img width="909" alt="Screenshot 2022-03-09 at 18 57 10" src="https://user-images.githubusercontent.com/93924525/157516932-964657a0-bf80-436e-b54a-1223a44ee734.png">

But it was implemented with pretty severe shortcuts if not incorrectly (current state)
<img width="842" alt="Screenshot 2022-03-09 at 19 18 04" src="https://user-images.githubusercontent.com/93924525/157516772-8d2cb736-e834-40e2-93e4-94630b37570e.png">

## ℹ️  Importantly

On the accounts page, more information could be shown wrt account locks, this was designed but we never got to implementing this and it looks like we can have a refresh here. While this IS a separate ticket, we can consider this in designing the above 3 points.

- #1556 

We have already a design ticket to create iconography for account locks. 

- #2354 

Designs done to date are here  [Link to Figma >](https://www.figma.com/file/pgNl83wgAub186krVkdiuo/Proposals?node-id=27%3A2774)

## Scope

1️⃣ 
- [ ] When account lock becomes recoverable - add notification (both alert and notiff?) for user. Account lock for {{name_of_process}} is removed and your stake can be recovered. > hyperlinked to /members and relevant account expanded 
![Screenshot 2022-02-22 at 15.16.58.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/c3c829a2-f958-40df-8f9c-9336a296250f)

2️⃣  Handle showing accounts with locks
- [ ] Voting stake. ["Sealed and not sealed"](https://joystream.gitbook.io/testnet-workspace/system/council#conditions-4). Its locked when you vote for a candidate. It remains locked while candidate is a councillor.
- [ ] Candidate lock - locked while yiou're a candidate, also transitions to councillor lock if you win.
- [ ] Proposal lock - autoremoved if proposal rejected or executed.
- [ ] Role staking account - role-specific lock
- [ ] Bounty work entrant staking account - locked while in bounty

3️⃣  Handle the case when there are NO accounts suitable

**Comment by dmtrjsg** [comment]
After driving it via quick jsg internal review, the suggestion here to apply a stronger messaging around account locks consequences more upstream, namely in the flows for each transaction that involves staking and imposing of locks: 

- Announce Candidacy
- Create Proposal
- Apply to WG Opening
- Announce Bounty  Work Entry

So let's revisit the corresponding the flows and see if we can find the right treatment for all cases. An info box, with simply put explanation of what can and cannot be done with this account after staked, and duration is smth that crosses my mind here.

**Comment by dmtrjsg** [comment]
Comment from Bedeho: "Here I think we can be more helpful, either the situation is fixable, or its not, and if its fixable, we should propose a very specific fix. A fix will be some mixture of possibly making a fresh account, binding, and transferring funds. We should explain what we are proposing to do, perhaps visually, and then offer a one-click action which does it all."

I am thinking we can split it into 2 parts, 

To-do now: elaborate on the case when available balances are all locked up, and only possibility is to create new acc and transfer funds from locked accounts. Account needs to be binded with this member, but I think if new acc is provided we bind it in the same transaction as step 1.

One-click action is still on the cards, but taking the liberty to add to to backlog and refocus on this as part of optimisation, rather than stabilisation and bugfixing phase.

**Comment by dmtrjsg** [comment]
+ For case when there are insusfficient funds on all acacounts add a blue info panel instead of CTA "Earn more tokens from Bounties and Working Groups Roles"

**Comment by MattAugustynowicz** [comment]
• Added ability to go directly from modal to bounties / working groups when there are insufficient funds [here](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=8718%3A296677)
• Added scenario where with locked accounts, we propose the user create a new one to move funds [here](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=8782%3A416805). If there is such a possibility, can we immediately fire off the creation of a new account instead of showing the first screen of the Polkadot plugin? 

<img width="1366" alt="image" src="https://user-images.githubusercontent.com/95480823/164517515-1e690153-4dce-4f24-b3ec-8f6579d711f1.png">

• Small text changes in modals (Suggestions copy)
• Added infotip icons for account locks in [My Account] (https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=8759%3A393512) page, in which we describe the lock in one sentence and add a learn more link to the gitbook

**Comment by dmtrjsg** [comment]
Based on this comment: https://discord.com/channels/811216481340751934/813361923172335648/966932874026709072
Suggestion to re-inforce the message that linking multiple accounts to one membership is beneficial for the rep accumulation. 

So perhaps add a line of copy stating > "It is strongly recommended to link all accounts to single membership in order to correctly attribute accumulated reputation on the network."

@MattAugustynowicz
