### ISSUE TITLE
Bounties: misc cosmetic issues

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2390]
## Create bounty flow

**Stage 1** 

- [x] Add text wrapping to the bounty description, similar how its done for proposals
- [x] Violation of Bounty Title does not prevent from bounty creation. To-do: disable core CTA if some of the forms show input validation error.

**Stage 2** 
**Cherry**
- [x] Add cherry tooltip
"Bounty creator has to put up an initial bounty, called a cherry, which is split among all contributors pro-rata in case bounty fails. This cherry generates an incentive for contributors, as even when the funding fails, they get a benefit. In case bounty succeeds, cherry is returned to the creator in full at the time, when Oracle submits judgement."
[Learn More>](https://joystream.gitbook.io/testnet-workspace/system/bounties#assurance-contracts-and-dominant-assurance-contracts) 

**Funding Range**

- [x] Add funding explainer text (between title and fields input). 
Define funding range. Working Period stage commences when minimal range is funded in limited funding type, and maximal range for perpetual funding type.
- [x] Add tooltip to minimal range: "Cumulative funding must be above minimal range for bounty to proceed to Working Stage period in limited funding."
- [x] Add tooltip to maximal range"Cumulative funding must be above maximal range for bounty to proceed to Working Stage period in perpetual funding. If a contribution is made that brings the cumulative funding equal to or above the upper bound (maximal range), then the difference is returned, and the bounty proceeds to the Working Period stage. Lastly, if the funding period is limited and the time passes this time, then the bounty proceeds to the Bounty Failed stage if there was at least one contribution made, otherwise it proceeds to the Expired Funding Period stage.
[Learn More >](https://joystream.gitbook.io/testnet-workspace/system/bounties#concepts)"

**Stage 3** 

Bounty Type 
- [x] Add tooltip to bonty type toggle open/close: "There are open bounties, where any member can participate, and closed bounties, where the creator can pre-select a set of members who can participate."
Min entrant stake
- [x] Update validation error for minimal entrant stake  to: Must be greater than {{minimum}} (since condition is set to strictly >)

## Bounty Card
- [x] Bounty ava Image seems to be hardcoded (and different to the image in details, which was correctly uploaded but NOT trimmed)
- [x] Member Avatar needs to show the profile pic : [designs> ](https://www.figma.com/file/jZwIoaxOkTxNFMJNzssBgv/Bounty?node-id=392%3A252407)
>current state is in comments, _Image 1_
- [x] Bounty creator avatar also has fitting misalignment
> image 2 in the comments
- [x] Entire bounty card needs to be clickable (not just chevron). On hover over bounty card - change cursor to pointing finger.
~Election number badge needs to show elections at which it was created (seems like # 6 is hardcoded)~
~Hide Funding badge - (informed by the budget, from which it is funded by the council, out of scope now)~
- [ ] Time left component on the card seems to be hardcoded (not counting down with every, every x blocks)
> img 4
- [x] For perpetual bounties also show [this component](https://www.figma.com/file/jZwIoaxOkTxNFMJNzssBgv/Bounty?node-id=429%3A230948), but with "ongoing", use the font that is used for numbers (font tbc)
- [x] Bounty funding progress bar missing
>img 6 in the comment w images 

## Bounty Details Page
- [x] Extra empty "winners" tab
- don't do: "Oracle widget -> Displays creator member rn, needs to show Oracle" as already captured here> #2659 

## Contribute
Rename Staking Account to "Select account" - there is no staking involved here

## Sign funding transaction
All copy must be on one line:
<img width="899" alt="Screenshot 2022-03-10 at 19 30 46" src="https://user-images.githubusercontent.com/93924525/157740296-8fbe5bf0-263f-4c59-8c6a-2b293bddd12c.png">

## Confirmation of Contribution
Update to "Your contribution is added successfully!"

**Comment by dmtrjsg** [comment]
Image 1:

![Screenshot 2022-03-02 at 18.09.25.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/d38aecd1-841c-48dc-8026-4b3c024d4858)

Image 2

![Screenshot 2022-03-02 at 18.09.36.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/2baa218e-9a72-4006-a5f0-e4b9571b2e79)

Image 3
![Screenshot 2022-03-02 at 18.17.42.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/a007fc31-2f27-4bc3-becd-e47d1f0a6900)

**Comment by dmtrjsg** [comment]
@bedeho  question:

❓  Is this component (see img below) informed by the WG or Council budget, which gets selected by proposal creator (council member) in the Create Bounty Proposal?

[Figma link >](https://www.figma.com/file/jZwIoaxOkTxNFMJNzssBgv/Bounty?node-id=285%3A116915)

Preview:
<img width="543" alt="Screenshot 2022-03-02 at 18 50 22" src="https://user-images.githubusercontent.com/93924525/156428629-f7d02913-530d-417b-ab66-aa327500a207.png">

**Comment by bedeho** [comment]
I think this is actually just tags. I am not sure we actually have even implemented this, but as you can see from the filters you can filter on tags in this design. Not 100% sure, but that is my best bet.

**Comment by dmtrjsg** [comment]
Removed preview, updated the estimates

**Comment by dmtrjsg** [comment]
#2749

**Comment by ivanturlakov** [comment]
Verified on staging. 

Create Bounty Flow - ok
Bounty Card - ok
Bounty Details Page - ok
Contribute - ok

**Sign Funding Transaction**
Possible problems with modal window visibility on screens with height less than 1600 pixels.
Tested on macbook 13, 2560*1600.
Also relevant to the Announce Work Entry. 
<img width="1440" alt="Снимок экрана 2022-05-05 в 17 19 49" src="https://user-images.githubusercontent.com/46903215/166944164-cabaa9c4-3a8b-480e-bb12-96e3bfc3c1d3.png">
<img width="1440" alt="Снимок экрана 2022-05-05 в 17 26 11" src="https://user-images.githubusercontent.com/46903215/166945362-c86fcbf6-9c3b-41dc-9dee-f9d6e5a0a610.png">

**Confirmation of contribution**
Update to "Your contribution is added successfully!"
Looks like it hasn't been changed yet
<img width="743" alt="Снимок экрана 2022-05-05 в 17 30 49" src="https://user-images.githubusercontent.com/46903215/166946622-6034b135-02d7-4fee-bf27-b0e71bd0022a.png">

**Comment by ivanturlakov** [comment]
@dmtrjsg I'm not sure, perhaps the problems of the modal window have already been noted in a separate ticket.
