### ISSUE TITLE
QA Bounties Module

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2568]
### Context

Pioneer dev team is opening up the early version of Bounties module for community testing. This ticket is aimed to encapsulate the efforts of Bounties Quality assurance.

### To-do:

- [ ] Conduct QA of bounty module and capture and report all bugs as comments to this ticket.
- [ ] ⚠️ Avoid raising duplicates, via reviewing the list of pre-existing issues. Use label **"scope:bounties"** to locate and review the content of the bugs already raised.
- [ ] ✅  We advise to start with the scenarios which are marked with **"to-test"** status on this [Notion board.](https://grizzled-corleggy-af8.notion.site/6b91ac8360704a36b244ca7d26847f61?v=eec3d21b7cdb475aaab0284cc1506ec8)

### Additional info
[Link to Figma - Bounties >](https://www.figma.com/file/jZwIoaxOkTxNFMJNzssBgv/Bounty)
[Link to Handbook - Bounties >](https://joystream.gitbook.io/testnet-workspace/system/bounties)

Dev Epic Link (see for open and closed child issues):
- #1302

**Comment by mochet** [comment]
Page: `Cherry`
Notion Link: https://grizzled-corleggy-af8.notion.site/6b91ac8360704a36b244ca7d26847f61?v=eec3d21b7cdb475aaab0284cc1506ec8&p=c83db28d00c94dbc8187af5fd14d7b9a
Test condition: `If bounty fails and cherry is set up`
Expected Result: 
`cherry is split between all contrinbutors equally* If undevidable equally, the first funder in the list gets an extra 1 Joy.`

Actual Result: all contributors got the same payout, account was left with 1 JOY and then a `system.KilledAccount` & `balances.DustLost` (with `1 JOY`) occurred: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2F54.160.70.85.nip.io%2Fws-rpc#/explorer/query/0x6143dd0eba20904b36c74e94ab954c3c158b7c6ba760bf5c9763fada57d9a9f2

**Comment by mochet** [comment]
(I can see other people doing actions on the chain, so writing the next thing I'm working on and will edit this once its done to avoid any confusion)
Page: `Cherry Return to Creator`
Notion Link: https://grizzled-corleggy-af8.notion.site/6b91ac8360704a36b244ca7d26847f61?v=eec3d21b7cdb475aaab0284cc1506ec8&p=cc1689b5d8224853bc49c4b02a28984e
Expected Result: `cherry is returned to creator automatically`

**Comment by mochet** [comment]
(I can see other people doing actions on the chain, so writing the next thing I'm working on and will edit this once its done to avoid any confusion)
Page: `Funding Period`
Notion Link: https://grizzled-corleggy-af8.notion.site/6b91ac8360704a36b244ca7d26847f61?v=eec3d21b7cdb475aaab0284cc1506ec8&p=562cafee326d44f7a5607245774a4cd4
Test Condition:  `"if a contribution is made that brings the cumulative funding to or above the lower bound (minimal range), the bounty proceeds to Working Period stage."`

**Comment by mochet** [comment]
(this one has already been covered quite a bit, but I did an additional test for a perpetual bounty type + extrinsic submission for good measure)
Page: `Funding Period`
Notion Link: https://grizzled-corleggy-af8.notion.site/If-a-contribution-is-made-that-brings-the-cumulative-funding-equal-to-or-above-the-upper-bound-maxi-dc702a4c87be421ea9c4d0183eaa9600
Expected result: `then the difference is returned, and the bounty proceeds to the Working Period stage. `

Actual result: The difference isn't returned, the transaction that goes through is actually just restricted to the `max cap`. So if `max cap` is 946 JOY and 1500 JOY is sent in funding, then only 946 JOY will actually be sent (via both pioneer and extrinsic)

**Comment by mochet** [comment]
(I can see other people doing actions on the chain, so writing the next thing I'm working on and will edit this once its done to avoid any confusion)
Page: `Funding Period - Failed Stage`
Notion Link: https://grizzled-corleggy-af8.notion.site/6b91ac8360704a36b244ca7d26847f61?v=eec3d21b7cdb475aaab0284cc1506ec8&p=2b2bf15210e34392930a8c2b010f3472
Expected result: `then the bounty proceeds to the Bounty Failed stage`

In progress

**Comment by mochet** [comment]
(I can see other people doing actions on the chain, so writing the next thing I'm working on and will edit this once its done to avoid any confusion)
Page: Funding Period - Expired Funding Stage
Notion Link: https://grizzled-corleggy-af8.notion.site/6b91ac8360704a36b244ca7d26847f61?v=eec3d21b7cdb475aaab0284cc1506ec8&p=08cba39ea44c439fb9027d9428256d2b
Test condition: `F funding period is limited and the time passes this time, and no contributions were made `
Expected result: `it proceeds to the Expired Funding Period stage.`


In progress

**Comment by mochet** [comment]
(I can see other people doing actions on the chain, so writing the next thing I'm working on and will edit this once its done to avoid any confusion)
Page: `Working Period - Whitelisted`
Notion Link: https://grizzled-corleggy-af8.notion.site/6b91ac8360704a36b244ca7d26847f61?v=eec3d21b7cdb475aaab0284cc1506ec8&p=8e5d793ca4d649619b92e8b53f545080
Test Condition: `Only Whitelisted members can take part`

in progress

**Comment by mochet** [comment]
@dmtrjsg @bwhm 
## Unreported Pioneer Bug - Creating closed bounty with whitelist generates `Transaction has a bad signature` error
* When creating a "closed" bounty and adding whitelist members the forum thread transaction goes through fine, the subsequent transaction to create the actual bounty fails with `Failure` message saying transaction has been canceled.
* Console output says `Transaction has a bad signature`
* Tried twice: 1x perpetual, 1x limited--both from different user accounts.
* The only reference to something similar I could locate was about https://github.com/Joystream/pioneer/issues/2492#issuecomment-1061221561

![image](https://user-images.githubusercontent.com/50830161/158652710-21cdca82-bf82-4894-ae9a-0825a6ed72a9.png)
![image](https://user-images.githubusercontent.com/50830161/158652732-07ceed19-1e7f-4dbb-b027-ced82d33d53e.png)

**Comment by mochet** [comment]
### Unreported bug - putting entrant stake at exactly 100 (the minimum) will not allow to proceed to next page
![image](https://user-images.githubusercontent.com/50830161/158961198-c05bea50-3e3e-48fc-9711-0bc4f7117af6.png)
Must be 101 or greater to work.

**Comment by dmtrjsg** [comment]
Thanks for this, just re-checked again and all issues seem to be already addressed in respective issues!
