### ISSUE TITLE
Fix the problem with withdrawing when cherry applies (when 0 contributions)

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2600]
## To-do

- [x] Add correct states for Cancelling Bounty if Contributions <0.
- [x] Cancelling bounty returns cherry to creator

## Context

Currently cherry is considered by the system as contribution. This translates to a bug.. 

When bounty is created with Cherry, and zero contributions were made, bounty transits to "Failed", and creator is able to withdraw their cherry (cherry right now is treated same as contribution in this case).

There is a bug, where withdrawal amount gets double-counted (contribution withdrawal + cherry, where cherry = contribution amount).

See image, Creator is listed in the contributors tab (since added cherry); withdrawal amount assumes cherry must be added on top of contribution, since that member was the only contributor>

<img width="705" alt="Screenshot 2022-03-21 at 09 21 41" src="https://user-images.githubusercontent.com/93924525/159242068-1613b26a-7c6e-449e-b3fe-30fc1fff7b3a.png">
  
_________________________
## Info on how Cherry should work in all cases

Change the logic of handling cherry, as per the following conditions.

0️⃣ 
Starting condition: Bounty created with 100 JOY set up as cherry.
>Bounty enters funding period

#### FUNDING PERIOD

**1️⃣  
**IF no contributions were made,** (only cherry was set up during bounty creation), bounty funding period ends, and it enters "funding expired" period. 

- [x] Creator can Cancel bounty from GUI. Button to display "Cancel bounty". Cancel bounty triggers returning cherry back to creator automatically .**

2️⃣ 
**If creator made a contribution in addition to cherry,** and bounty enters "Expired funding period" (e.g. if contribution was insufficient to transit to Working Period stage, and bounty funding period fails.

- [x] Creator sees Display Withdraw Contribution CTA, on click, allow to withdraw original contribution + cherry (since creator status here is superceded by contribution, so withdrawal happens for the contributor). 

⚠️  This point depends on this ticket in design #2341 

3️⃣ 

**If contribution was made by a member, who is not creator, but bounty fails due to insufficient funding (..and enters "Withdrawal period")

- [x] Creator does not see any withdrawal buttons, and can do nothing with bounty.
- [x] Contributor sees "Display Withdraw contribution CTA". On click, allow to withdraw original contribution + cherry here, external contributor withdraws their funding AND cherry. Since only one member contributed, that member gets 100% of cherry on top of his own contribution, when withdrawing.

⚠️  This point depends on this ticket in design #2341 

#### WORKING PERIOD

4️⃣  **If contribution was made (in addition to cherry) and total contribution was enough to transit Bounty to "Working period" stage.**

Here two scenarios are possible:

4.1 Bounty fails (No active entries were made during Working period) -> 

- [x] Bounty goes to Withdrawal period. During withdrawal period, contributors withdraw their contributions + portion of cherry.

4.2 Bounty goes to Judgement period (entry announced, followed by work submitted).
 
- [x]  Cherry stays on the bounty account, awaiting outcome of judgement period

#### JUDGEMENT PERIOD

5️⃣  **If judging period gets expired, or fails (Oracle never made it on time to judge)**

- [x] Bounty transitions to Withdrawal period. Contributors can withdraw their contributions plus portion of cherry.

6️⃣  If Judgement was made by Oracle, but no winners were decided

- [x] Bounty fails, enters withdrawal period, Cherry is split among contributors. It gets credited to the contributors accounts on "Withdrawal" of contributions.

7️⃣  If judgement period ends with Judge selecting a winner

- [x] Submitting judgement transaction triggers crediting cherry back to creator.

**Comment by bedeho** [comment]
> If creator made a contribution in addition to cherry

In this scenario I am assuming the creator did the following two transactions in this order
1. https://joystream.gitbook.io/testnet-workspace/system/bounties#create-bounty
2. https://joystream.gitbook.io/testnet-workspace/system/bounties#fund-bounty

I would just treat this no differently as how any other contributor interacts with the bounty, we don't need some special handling and convenience, at least at this stage, for the scenarios where a creator also goes and contributes independently. This seems like the path of least resistance, correct me if I am wrong, could be the case as its 

> If contribution was made by 1 member, who is not creator, but bounty fails

Product wise this is identical to case 2.

>  4. If contribution was made by creator, in addition to cherry and contribution was enough to transit Bounty to "Working period" stage.

This still depends on what sort of judgement occurs:
1. no judgement (oracle in Bahamas): not returned, split among funders.
2. no winners in judgement: not returned, split among funders.
3. winners: is returned automatically when judgement is submitted, I updated the handbook to mention this.

Now, obviously the creator still ultimately gets the cherry in 1&2, but its not _as the creator_, but _as the funder_, which I took to be a key distinction in the question.

> 5.  if contribution was made by non-creator and it was enough to transit Bounty to "Working period" stage.

Product wise this is identical to case to 4.
