### ISSUE TITLE
Add FM/$JOY information banner

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#2824]
# Background

So I know I have been quite religious about not allowing Jsgenesis policy stuff to leak into Pioneer, but the recent catastrophic information failures have really tipped the scales for me.

# Proposal

Add some sort of well done banner at the foot of the app, similar to what we had in Pioneer one, which tries to explain to users that 

1. We are currently on testnet, not mainnet.
2. $tJOY earnable here translates to mainnet $JOY through the FM program.
3. Then we can have perhaps a button that send you to talk to integrators to step into a role.

The banner should be hideable by clicking some sort of _close_ button, and this choice can just be stored in local storage. I think @toiletgranny could be great for making the visual on this, he already did a sweet job for Pioneer one, as I think @MattAugustynowicz is not going to be available short term.

### Scope

Add banner with tJoy earning info.

Design Acceptance Criteria:

**For guest users**
- [ ] Banner shows for all guest users with headline, paragraph and two ctas
- [ ] Do not show this again checkbox (state stored in local storage and persists across sessions)
- [ ]  CTA pointing to _Speak with integrators to start earning_
- [ ] would need to co-exist with privacy policy banner (**:warning: NB:** design on privacy policy for pioneer is still in the pipe and not started, so this needs to go on assumptions)

**For users with selected membership**
- [ ] Displays how much $USD equivalent value earned so far in $tJOY
- [ ] Displays how much $tJOY earned
- [ ] Displays how many $USD they are missing before they can get verified (this value comes from CRM, currentl yits $5000).
- [ ] Displays how many $USD they are missing before they will be founding member, this value comes from CRM, currently its $15000.
- [ ] Displays what when this information was last updated.
- [ ] Has button linking to full profile in CRM.

**Comment by traumschule** [comment]
If a membership is selected it could like to the according [CRM profile](https://joystream.retool.com/embedded/public/9478bcc0-f6d6-4f74-bd0a-0637535e75b1).

**Comment by bedeho** [comment]
Yes this is a very good idea!

**Comment by traumschule** [comment]
> @traumschule thanks for adding the idea, need your help to make it happen (assume you are managing the CRM?)
that would be @blhrc, please add him as collaborator to the repo to ping.

> what would be the best destination for initial conversation with integrators?
https://discord.com/channels/811216481340751934/943152435432669266

**Comment by blrhc** [comment]
> 2️⃣ On the second note of showing the link to own membership, also need to clarify what the url structure, what does this bit stand for (see img)?
Not sure what it stands for - perhaps you could phrase the question differently?
It's just a link to a public view of the UI.

There is a URL token at the end "personid" which isn't actually "memberid" as in Pioneer, so that needs to be changed to allow linking from there. I'll fix this and get back to you, but let me know if there is anything else you need meanwhile.

**Comment by dmtrjsg** [comment]
@bwhm 

Questions:
1. Guest view (IMG1 below, wallet not connected) banner shows a link to “start earning” but essentially needs to point to Discord channel aka “Speak with integrators”. What would be the right URL for this?  
<img width="838" alt="Screenshot 2022-05-31 at 12 53 14" src="https://user-images.githubusercontent.com/93924525/171105378-97705671-5aa0-44dc-a2fb-d050545f8de8.png">

2. I found [this article](https://support.discord.com/hc/en-us/articles/115001542132-Custom-Invite-Link) about the custom links to discord, and caveat is that it requires for free open channel where we want to point users is on the very top. Does this mean we need to re-org the discord channels? Who is the best person to assist with looking into this deeper?
3. For logged in members the aspiration is to display the progress bar towards verification / FM status (IMG2 below). The JOY-USD conversion rate - where is that parameter defined and stored?
<img width="923" alt="Screenshot 2022-05-31 at 12 56 46" src="https://user-images.githubusercontent.com/93924525/171105374-ec3b65bf-fc5d-4ad9-9a73-f4f435bdc64f.png">
4. Thresholds for Verification and FM programme of (5k and 15k) - shall we hardcode this, sing this presumably not going to change before mainnet?

5. The CTA on the logged in member view must be pointing to this member CRM profile. Who is the best person to update the URL structure in the CRM tool to match the memberID? 
6. On the URL structure in the tool, before the URL token with member ID it has some sort of a hash (IMG3), is there a pattern that we can encode on our end to point to the right person? Thinking we may want to simplify the URL structure on the CRM tool, but not sure how this can be best achieved (and who to instruct to look into this right now)?
<img width="962" alt="Screenshot 2022-05-31 at 13 05 21" src="https://user-images.githubusercontent.com/93924525/171105366-83f80827-787d-4317-9c87-cefbfa5a3019.png">
<img width="595" alt="Screenshot 2022-05-31 at 13 04 29" src="https://user-images.githubusercontent.com/93924525/171105372-bdc61a3e-2200-44ba-b56e-04e78d9d7dd8.png">
7. Lastly, am I correct with assumptions that FM and tJOY info on gitbook is up to date? (IMG4). While in design brief and figma mocks the statement was that conversion of tJoys into JOYs happens via FM program, gitbook only specifies the tJoys to BCH conversion..  I feel like need some steering on this as was not following this through very recently. 

<img width="620" alt="Screenshot 2022-05-31 at 13 12 56" src="https://user-images.githubusercontent.com/93924525/171105354-3959fcb2-39ee-41e4-8d74-7ff58394681a.png">
<img width="702" alt="Screenshot 2022-05-31 at 13 10 41" src="https://user-images.githubusercontent.com/93924525/171105362-647455f1-3dc8-430a-8846-34a26fe3d716.png">
<img width="748" alt="Screenshot 2022-05-31 at 13 09 27" src="https://user-images.githubusercontent.com/93924525/171105365-a351a533-e3f4-407f-bc06-ca2ff164ddbf.png">

**Comment by dmtrjsg** [comment]
@MattAugustynowicz 

Few comments on required design iteration (same points are added to Figma bubbles)
1. We need a view where member has wallet connected but membership not selected
2. Copy needs to get updated on H1 and H2 for banner and CTAs for membership selection
3. I think we may benefit from ability to show/hide this banner via different mechanics (vs do not show this again), since the feature grew into showing progress bar which would need to be accessible after closing.
4. We need to design provision to show it together with privacy policy banner (similar to Atlas or Marketing website?) I ack we did not design for it yet, but would be nice to avoid clash at later stage.

..this feature is rather urgent 😇

**Comment by dmtrjsg** [comment]
Price https://status.joystream.org/price

**Comment by dmtrjsg** [comment]
Superseded by https://github.com/Joystream/pioneer/issues/3141 in favour of ultra expedience.

This epic (and all related tickets) will be kept for reference, marked as enhancement and closed for the time being.
