### ISSUE TITLE
Overview – openings

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#287]
@[figma](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Design?node-id=199%3A3016)

### Requirements

- [x] Setup the Working groups page & stub empty pages #376
- [x] Implement "openings" tab of the working groups page #376
- [x] Display openings list #383 
- [x] Display upcoming opening lists #383
- [x] Display working group activities #384

#### In worker context:
- [x] Display my roles, staking, and earnings dashboard #390

### Missing or stubbed data:

- Currently staking #394
- User earnings #404

**Comment by jodator** [comment]
Let's mark it done. We have smaller tasks to finish tracked in #394 & #404.
