### ISSUE TITLE
Working group – openings

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#289]
@[figma](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Design?node-id=16%3A2266)

### Requirements

Implement the Working group "overview" tab.

*   [x] Prepare base page components, empty tabs.
*   [x] Display working group leader and workers.
*   [x] Display upcoming openings.
*   [x] Display opening details.
*   [x] Display active openings.

### Follow-ups:

*   Handle non-member "Notify me when it's open". Moved to: #414
*   Display working group dashboard (current budget, debt, stake, etc). Moved to: #415

**Comment by jodator** [comment]
Closed with follow-ups: #414, #415.
