### ISSUE TITLE
Open position preview

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#292]
@[figma](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Design?node-id=259%3A1652)

### Requirements

- Prepare opening page
- Implment opening dashboard
- Display opnening description
- Display opening application process
- Display list of candidates
- DIsplay different state of application (upcoming, etc)

### Questions

- Do applicaiton process is text-only or follows a protobuf schema?

**Comment by jodator** [comment]
@wyrdrender to help you out with the domain requirements for the opening screens we need. I've made a list below to track everything. It looks like almost every state of the opening has a bit different set of components.

1.  Upcoming opening (this one requires mocks, but let's wait for #548 PR as it should ease with mocks creation).
    *   [x] Notify button (no action for now)
    *   [ ] Empty applicants list (this opening hasn't started)
    *   [ ] dashboard - I think that it should have: 
        *   Time to start,
        *   Expected duration,
        *   reward per 3600 blocks
        *   applicants + hiring limit
    *   [ ] created at block time
2.  Opened (active) opening
    *   [x] copy/apply now
    *   [ ] when no applicants (no applicants info + apply now)
    *   [x] applicants list
    *   [ ] dashboard:
        *   time left
        *   minimal stake or my stake (when my application)
        *   reward per blocks
        *   current applicants + hiring
    *   [ ] created at block time
3.  Closed / cancelled
    *   [x] copy link
    *   [x] applicants list 
    *   [ ] info hiring complete if there's my application (currently it is always shown)
    *   [ ] dashboard:
        *   (first ?? -> I'll check that one),
        *   reward per blocks
        *   minimal stake or my stake (if my application)
        *   applicants + hired
    *   [ ] closed at block time

General information:

*   [x] badges
*   [ ] short description (AFAIR text-like)
*   [x] description (Markdown like)
*   [ ] application process (`details` field) (Markdown like)

**Comment by jodator** [comment]
I think that we can close this one. The milestone needs a review anyway, so the remaining things are moved to: #647
