### ISSUE TITLE
Apply for a position

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#293]
@[figma](https://www.figma.com/file/QSpueQlOQKGbiHig2harPy/Working-groups?node-id=1080%3A4837275)

### Requirements

*   [x] Implement modal with steps containing application steps and role description (#416)
*   [x] Implement the "stake" step (#417)
*   [x] Implement application form (might be a general handler) (#418)
*   [x] Implement application transaction submit & submitted state (#419)
