### ISSUE TITLE
Pioneer and Carthage Runtime QA 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3217]
# Context
New runtime release - `carthage`
* https://github.com/Joystream/joystream/issues/3666

Overarching test plan:
- #3403 

# Testing Env Details

ℹ️ Playground config details: https://54.172.154.45.nip.io/network/config.json
Pioneer Instance: https://dao-git-carthage-joystream.vercel.app/
Current council size is set to 1; WG leads are pre-hired with each WG has 1 worker; Alice account has JOY balances.

☝️ Pls don't forget to point Pioneer env to the Carthage playground:
https://dao-git-carthage-joystream.vercel.app/#/settings?network-config=https://54.172.154.45.nip.io/network/config.json

And choose Auto-conf from the settings afterwards:
<img width="607" alt="Screenshot 2022-07-29 at 19 24 48" src="https://user-images.githubusercontent.com/93924525/181821619-660193ad-64c5-4003-94b2-bd4c75e1959a.png">

☝️  NON-Pioneer issues refer to the resources file, which has details on how to execute network testing:

[testing-resources.zip](https://github.com/Joystream/pioneer/files/9222717/testing-resources.zip)

# Scope
The focus of Carthage release is primarily on transaction fees estimates and calculation, and due to ubiquitous nature of this change we need to ensure that all critical DAO processes work on the new runtime version. 

* [ ] Perform regression testing of all processes (complete all tasks from point 1)
* [ ] Raise all bugs in Pioneer project and list them in the comment to this ticket
* [ ] Complete general new runtime version testing (part 2)

☝️ For each child issue, please read the requirements to capturing and documenting the observations on transaction fees.

## Important:

☝️ 🐛 For Runtime and QN bugs, feel free to raise them directly in the repo and add labels 
☝️ 🐞 For Pioneer issues and Atlas, pls raise the found bugs using USERSNAP widget 

<img width="163" alt="Screenshot 2022-07-29 at 20 27 03" src="https://user-images.githubusercontent.com/93924525/181830675-22961b22-0e0a-40f0-9ad3-eae999f77e7e.png">

 
# Child issues:
 
 For @ ivan T and @ oig_res:
 
* #3301 
* #3302 
* #3303 
* #3407 
* #3304
* #3404 

Non-pioneer Issues (created here for convenience):

For @ traumschule and @ freakstatic 

* #3405 
* #3411 
* #3412 
* #3413 
* #3414

Out of scope:

* #3406 ⚠️

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202591149543151) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
This Epic is not Complete. 

2nd round of testing is undertaken in 
- https://github.com/Joystream/pioneer/issues/3577
