### ISSUE TITLE
Info: Test Plan

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3403]
:warning:  Playground config details: https://54.172.154.45.nip.io/network/config.json
:warning:  Pioneer Instance: https://dao-git-carthage-joystream.vercel.app/
Current council size is set to 1; WG leads are pre-hired with each WG has 1 worker; Alice account has JOY balances.

* [Introduction](#introduction)
  * [Testing Phases](#testing-phases)
    * [Initial Testing](#initial-testing)
    * [Full Testing](#full-testing)
    * [Final Test](#final-test)
* [Resources](#resources)
* [Initial Testing Scope](#initial-testing-scope)
  * [Staging Network Parameters](#staging-network-parameters)
    * [Notes and Bug Reporting](#notes-and-bug-reporting)
  * [Validation](#validation)
  * [Pioneer](#pioneer)
    * [Election Success](#election-success)
    * [Proposals 1](#proposals-1)
  * [Content System](#content-system)
    * [Curators](#curators)
    * [Storage](#storage)
    * [Distribution](#distribution)
    * [Creation](#creation)
    * [Curators](#curators-1)
    * [Vesting](#vesting)

# Introduction
The purpose of this document is to lay out a detailed, and fairly extensive testing plan for carthage. The bulk of the testing will be performed by the community, with input and supervision from Jsgenesis.

The main changes from Rhodes to Carthage, and their consequences for QA work, are:

* Upgrading to Substrate V3.
  * means that we may experience bugs with everything and anything
* Integrating fixes from recent quarkslab audit.
  * NA
* Creator tokens pallet: not exposed in Atlas. _and;_
* Creator payouts features: not exposed in Atlas or Pioneer.
  * means it requires more effort to test
* Bounties V2: not exposed in Pioneer.
  * means it requires more effort to test
* Various improvements and bug fixes.
  * NA
* Real token issuance. _and;_
* Genesis accounts with vesting and multisignature ownership.
  * means `vesting` needs to be tested for all apps
  * `multisig` unlikely to be supported outside of polkadot-js for first round of testing
* Fully benchmarked runtime on reference hardware.
  * NA
* Introduction of non-zero fees.
  * means all apps should make estimates for fees and never let a transaction fail without a warning/rejection if you have insufficient balance (or worse, try to push a TX without fees)
* Rollout with sudo phase which filters non-essential extrinsics while bootstrapping.

## Testing Phases
We divide the testing in to three phases, as defined below:

### Initial Testing
During this phase, we assume:

* Pioneer 2.0 is working, but untested and without some important features.
  * Unclear how well/if fee estimation works
  * Vesting likely not handled, meaning;
    * you can't free vested (eg. locked) tokens (in pioneer)
    * you can't see your vesting schedule
    * potential issues in distinguishing between free balance, tokens locked due to vesting and "other" locks
    * you may not be able to use vested tokens for purposes you "should" be able to
    -> your balance may not reflect reality
  * Unclear if the new address format is parsed correctly
  * Lots of bugs should be expected
* CLI expected to work, but similar to Pioneer it's untested and without some important features
* Polkadot-js should work flawlessly, but is hard to use for some transactions
* Query node is working, but lots of bugs likely
  * Instances of the query node should be inspected frequently
* Content system (`colossus` and `argus`) expected to work
* Atlas unlikely to work flawlessly from the start
  * not be a focus for this testing plan, except making sure content distribution works
  * expect playback to work, but creation, uploads, updates and nfts may not

This phase will end once we reach a point where all the individual modules/apps has been tested and issues has been made for each and all bugs uncovered. At this point, we should have a list of:

* everything that has been tested
* a summary of how it was conducted, with results
  * if a problem was found, a link to the issue made
  * if a part of the test was blocked due to issues found in "earlier" steps, a description of what is remaining and a link to the dependency (issue)
* everything that was not tested due to missing features

The line between when this phase ends and the [Full Test](#full-testing) begins may be somewhat blurry for some parts of the test.

See [Initial Testing Scope](#initial-testing-scope) for details.

### Full Testing
This stage expects all applications and features expected to be supported, and bugs uncovered during the previous phase to have been addressed. Parameters should be the preliminary ones we expect for `carthage`, but are still open for change. Some time during this stage, we expect the fee benchmarking to be completed.

This will likely be the longest phase, with lots of resets.

### Final Test
This should be a "dry run" of the `carthage` launch, and unless something critical occurs, the release happens one of the following days.

# Resources
Scripts, inputs and/or guides for the following can be found in the resource folder

* Deploy (channel+video) categories scripts
* Storage setup and bucket deployment
* Distribution setup and bucket deployment

# Initial Testing Scope
The main focus of this test will be:

* Testing fees and vesting thoroughly across the board
  * eg. runtime AND "all" apps (ex. `atlas`)
* Testing the content system thoroughly
  * making sure content is stored and distributed, and both the `argus` and `colossus` server+CLI are handling fees, address formats and vesting (not critical, but we need to know if not)
  * `joystream-cli` support for all actors (owners, maintainers and curators) to perform their core tasks
    * owner+maintainers can create, update, delete
    * curators should be able to update, censor and delete what they have permission for
* Regression test of Pioneer and query-node will be performed during the Full Testing stage
  * as the upgrade of substrate may cause unexpected bugs, everything (except bounties) that used to work may not anymore
  * for this test, we'll focus on ensuring the basic flows works

Note that several staging networks may be deployed simultaneously to avoid having testers stepping on each others toes (eg. council election flows and proposals).

Performing the tests (efficiently) requires using some combination of:

* CLI
* Scripts
* polkadot.js

## Staging Network Parameters
This network should have the following properties:

* 2 `validators`, 1 `endowed` and a `sudo`
* No council elected, no Leads hired
* Short election cycles (eg. Announcing/voting/revealing/idle: 100/50/50/100), preferably 3 CM slots (and 1 "extra candidate")
* Short proposal periods
* Short minimum unstaking for WGs (`pub const MinUnstakingPeriodLimit: u32 = 43200 -> 200;`)
* Preferable short `BONDING_DURATION`, but not critical
* May have some members, but this can be done with a script
* No vesting in genesis

### Notes and Bug Reporting
All the while, make notes of the fees for each transaction. The CLI _should_ give a fee estimate, which may or may not be 100% correct. Create and maintain a spreadsheet for this purpose. Polkadot.js should do the same, whereas for a script, that requires some extra work.

Issues encountered in pioneer should be reported directly with the plugin.

Issues encountered in atlas should be reported directly with the plugin.

Runtime or CLI issues should be reported by creating issues in the joystream repo.

## Validation
* [ ] Spin up a couple nodes, and join as a validator on one of them.
* [ ] In polkadot-js, create a new account ("stash") and make a `vesting.vestedTransfer()` of say 1 JOY for some amount to this new account. If at height `#n`:
  * locked: 1*10^9 u128 ($JOY 1)
  * perBlock: 1*10^4 u128
  * startingBlock: `n+20`
* [ ] Send some free tokens to another account ("controller"), and set up a validator.
  * Ensure you can use all (vested) tokens as stake for stash.
  * You may need to free some tokens, through `vesting.vest()`, for transaction fees.

### Election Success
* [ ] Go through a successful election cycle in Pioneer, by using the minimum values. Ensure:
  * Minimum values (# CM slots + 1 announces, # CM slots votes) is sufficient
* [ ] Go through another successful election cycle using Pioneer or a script. Ensure:
  * Stakes (candidacy and voting) for/on the previous CMs can be released when they should.

### Proposals 1
For each of the below, ensure:

* Your changes are executed on chain
* The proposers stake is:
  * freed (if approved)
  * freed minus fee (if rejected/expired/vetoed)
  * slashed (if slashed)
* Note down fees, and compare pioneer estimate to polkadot-js actual
**All the below should be tested in Pioneer**
* [ ] Go through the full "Hire Leads" flow. Hire: Curator, Membership, Forum, Storage, Distribution. All with:
  * some reward
  * "short unstaking"
  * make the opening application (descriptions, questions etc.) different for comparing fees. Note down what you did, the size and the fees.
  Ensure:
  * groups are named correctly
  * openings are rendered correctly
  * applications are presented correctly
  Once done -> Notify testers of [Storage and Distribution](#storage-and-distribution)
* [ ] Update Working Group Budget (for all relevant groups)
  * Use varying amounts, so that:
    * Curator group will not be able to pay the Leads "full" reward
    * Forum group will able to pay the Leads "full" reward exactly (need to calculate expected reward based on hiring block and [payout schedule](https://github.com/Joystream/joystream/blob/431031155d073f9a65f929abef5ebe441999ebf7/runtime/src/lib.rs#L1079)).
    * Storage group gets nothing
    * Distributor groups gets enough for Lead + 2-3 workers for a few days
    * Membership lots, so that members can be created through the faucet
    * After the above is approved, try making a proposal for MORE than what the council has in its budget.
      * Check that budgets and rewards are displayed and processed correctly (in pioneer and the QN) ref. [payout schedule](https://github.com/Joystream/joystream/blob/431031155d073f9a65f929abef5ebe441999ebf7/runtime/src/lib.rs#L1079)
* [ ] Signal
  * Check rendering
* [ ] Funding Request
  * Create in pioneer, with 1 recipient
  * Create in polkadot.js or script with >1 recipient
    * Check rendering and execution
* [ ] Set Councilor Reward
  * Check rendering and execution
* [ ] Set Membership Price
  * Check rendering and execution

## Content System
Once the required Leads have been hired:

### Curators
* [ ] Content Lead to create 15 video and channel categories
  * See resources
* [ ] Hire (at least) 3 more curators
* [ ] Create curator groups

### Storage
* [ ] Follow the steps as explained in the resources to:
  * Create buckets
  * Set various parameters and configs
  * Hire workers

### Distribution
* [ ] Follow the steps as explained in the resources to:
  * Create buckets
  * Set various parameters and configs
  * Hire workers

### Creation
* [ ] Create at least channels 6 with 2 videos in each
  * Make sure they are received by a (storage) liason and included in the "correct" amount of storage buckets and upon request
  * Make sure they are included in the "correct" amount of distribution buckets and upon request, "distributed"

### Curators
* [ ] Create multiple curator groups, with multiple permissions.
  * [ ] Try all actions for each group, eg. delete, edit, censor channel and video, and verify what should be allowed is, and vice versa.
  * [ ] Change the permissions for a group or two, and verify that the new permissions are in effect
  * [ ] Check if the Lead can perform all actions without being in any group

### Vesting
Try for a worker (or Lead) in any group.

* [ ] In polkadot-js, create a new (staking) account and make a `vesting.vestedTransfer()` of say 0.1 JOY for some amount to this new account. If at height `#n`:
  * locked: 1*10^9 u128 ($JOY 1)
  * perBlock: 100 u128
  * startingBlock: `n+20`
* [ ] Setup this account as a staking account for a member, and try to use it for applying to a role. Stake with 0.09 full amount (ex fees)
  * You may need to free some tokens, through `vesting.vest()`, for transaction fees.
* [ ] Assuming success:
  * How does a `system.account()` "look"?
  * How does the `balances.totalIssuance()` "look"?
  * How much can you transfer to ANOTHER account (`x` tokens, with `y` fees)
* [ ] Do a `vesting.vest()`:
  * How does a `system.account()` "look"?
  * How does the `balances.totalIssuance()` "look"?
  * How much can you transfer to ANOTHER account (`x` tokens, with `y` fees)
* Slash the Worker for half the stake.
  * How does a `system.account()` "look"?
  * How does the `balances.totalIssuance()` "look"?
  * How much can you transfer to ANOTHER account (`x` tokens, with `y` fees)
* Quit and unstake the Worker. Once done:
  * How does a `system.account()` "look"?
  * How does the `balances.totalIssuance()` "look"?
  * How much can you transfer to ANOTHER account (`x` tokens, with `y` fees)

Repeat the process for a proposal.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202691503754378) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
[initial-test.md](https://github.com/Joystream/pioneer/files/9213246/initial-test.md)
