### ISSUE TITLE
Pioneer Notifications

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4196]
## Context
- https://github.com/Joystream/pioneer/issues/2880

This issue encapsulates the design work for subscribing to email notifications, customising email notifications (in the settings module), and subscribing to specific entities such as Proposals, WGs and Forum categories and posts. 

👉 @design suggestion :
- Notifications management should be done in Settings > Notifications (new tab)
- add notifications drawer back to the app (the one that is sliding out when clicking on bell icon)
- We should make tx emails as an additional step in membership creation flow. Pre-populate by email if was provided before but make sure to inform them this will never be shared and used ONLY for tx notiffs. 
- For existing members: display info banner/ modal on first landing to the app after release "Provide email notifications. You can opt out and manage notifications in the settings later." Banner can be closed. 

Reusable parts of designs: 
- [add membership flow>](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-design?node-id=545%3A1811&t=FiWIQ8WBC8WZ1Q8r-1)

⛔ Out of scope: 
- Email and in-app notifications can be customised separately (design only but implementation will not have it in the first release)
- [notifications>](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-design?node-id=3600%3A73&t=fY4KAvf27HhQzdYK-0) 
- Notifications are handled in this matrix > https://github.com/Joystream/pioneer/issues/933

### Sign up to email notifications
As pioneer user I want to 
- [ ] enable notifications via providing my email during membership creation flow
- [ ] receive email verification link to my email 
- [ ] following the link get redirected to pioneer to sign the auth with my controller account (not blockchain tx)
- [ ] change my email
- [ ] stop all email notifications
- [ ] add accounts that I care about (to get notifications about revealing stage reminders)

### Customise email notifications

As pioneer user I want to customise which emails I want to receive:

#### Council 
- [ ] All council notifications
>---  announcing stage started
--- 1 day before announcing stage ends
--- voting stage started
--- 1 day before voting stage ends
--- revealing stage started (only for accounts that are voted)
--- 1 day before revealing stage ends

#### Proposals
- [ ] All Proposal notifications
>--- new proposals created
--- proposals voting complete (proposal rejected/ accepted)
- [ ] Personalised proposal notifications
>--- new discussion posts on proposals I watch

#### Working groups notifications
- [ ] All wg notifications
>--- new hires 
--- new terminates
--- new openings and applications
- [ ]  Notifications for each wg I watch

#### Forum
- [ ] New threads created in categories I watch
- [ ] New posts and replies to threads I watch

## Subscribing to email notifications
As pioneer user I can subscribe to notifications for 
- [ ]  Specific proposals to receive proposal notiffs (listed above) on proposal preview page
- [ ]  Specific working groups on working group details page
- [ ] Specific forum categories to receive new threads notifications on category page
- [ ] Specific forum threads to receive new posts notifications on thread page
- [ ] Specific forum categories I watch to receive notiffs on all posts and replies in this category

## Role-specific notifications
Councillor
- [ ] As a councillor I will have access to role-specific notification (once you stop being a councilor you will not have the notiffs) ⚠️ and the email itself can be different as in "you have that much time to vote on it"..
Work Group Lead 
- [ ] All applications in the working group
- [ ] Working group -related proposals (openings/ budget/ slashed/ terminates)

### Mute direct mentions
- [ ] choose from which discussions (forum threads/ proposal/ openings) you want this to mute (nice to have)

### Automatic subscriptions for specific roles

As any pioneer user I automatically subscribe to 
- [ ] proposals I create
- [ ] proposals I post to discussion thread to
- [ ] threads I create in forum
- [ ] threads I post or reply to in thread

As council member I automatically subscribe to 
- [ ] All proposals notifications

As WGL I automatically subscribe to 
- [ ] All wg openings applications in my WG

**Comment by dmtrjsg** [comment]
Bunch of events already created: 

// Forum
  FORUM_POST_MENTION
  FORUM_POST_IN_CREATED_THREAD
  FORUM_POST_IN_WATCHED_THREAD
  FORUM_POST_IN_CONTIBUTED_THREAD
  FORUM_POST_IN_MODERATED_CATEGORY

  // Proposal
  PROPOSAL_POST_MENTION
  PROPOSAL_POST_IN_CREATED_PROPOSAL
  PROPOSAL_POST_IN_CONTRIBUTED_DISCUSSION

  // Referendum
  ELECTION_ANNOUNCING_STARTED
  ELECTION_VOTING_STARTED
  ELECTION_REVEALING_STARTED
  ELECTION_COUNCIL_ELECTED

  // Councilor only
  COUNCILOR_PROPOSAL_CREATED
  COUNCILOR_POST_PROPOSAL

**Comment by dmtrjsg** [comment]
Issues from Bedeho: 

The announcement stage has started.
The voting stage has started.
The voting stage has started & there is at least one proposal with constitutionality > 1 which is either been confirmed this council or is still up for a vote.
The reveal stage has started & member has voted in this election: there needs to be an endpoint to manage list of accounts member cares about as "themselves", because voting is not a member-level action.
A council has been elected.
A specific thread has a new post: there has to be an endpoint to manage the list of threads the given user wants to monitor.
Someone @mentioned me in a forum post/thread.
Someone @mentioned me in a proposal post.
A post was made on a proposal, and I am a sitting council member: [use-case](https://discord.com/channels/811216481340751934/812343711870091285/1066086273112084602)
Somone made a post to a thread member created.
Someone made a post to a thread where member also has made a post.

**Comment by dmtrjsg** [comment]
@bedeho  would this case 

> The voting stage has started & there is at least one proposal with constitutionality > 1 which is either been confirmed this council or is still up for a vote.

be specifically needed for someone who is only interested in voting for councils during the multiple consitutionality proposals are in flight? Or should not the trigger be at the time when council is elected AND there's a proposal which requires this new council to act on?

Could you pls explain the desired outcome and target audience of this case vs how this compares to general `voting stage started`

**Comment by bedeho** [comment]
> Could you pls explain the desired outcome and target audience of this case vs how this compares to general 

This was a bit hard to understand, but my goal here is just to allow people to learn that some high stakes proposal is on its way to get passed, as it therefore may warrant them investing the time to figure out if this is a good idea, and if not, they would make their opposition heard by either standing for or voting in the next council which needs to confirm the proposal.

> unless we are thinking about the cases when voting will be done in the "anonymous" way (without membership)

Yeah that probably would be a good idea, many people will vote with accounts not associated with a membership.

> Overall suggestion is to exclude these cases from the MVP, unless they are deemed critical.

Sounds fine.

**Comment by dmtrjsg** [comment]
In-app notifications missing (as current designs only covered QN events). There's a lot of what is called activity and this needs to be remapped from QN to BE. Needs to be done case by case basis to enable Notiffs. 

MVP: All notifications that user subscribes to will be visible on the BE, but only for a subset you will receive the email notifications.

Example:
- Mentions
- New post is created

**Comment by thesan** [comment]
@dmtrjsg I have a few suggestions/questions:

First I think that in addition to the "New threads in categories I watch" subscription, there should also be a "New posts in categories I watch" one.

Also here https://github.com/Joystream/pioneer/issues/4085#issuecomment-1438230539 Bedeho suggested this scenario:
> 3. Bedeho should not receive notifications from thread=68 when someone makes a post, despite being mentioned there, becuase he has "unsubcribede" from this specific thread.

The db model needs to change a bit but it shouldn't be to hard. But this will need to somehow be added to the UI.

Same thing for the voter account (the db needs to keep track of them and it needs to be added to the UI). But does these voter account have to be verified too ? Just like any other notification tied to a membership (hence the verified controller account), it notified members of publicly available data but it could potentially give a convenient way to track other people too.

Finally I don't understand the "In-app notifications drawer" section.

**Comment by dmtrjsg** [comment]
Not MVP: 

> Same thing for the voter account (the db needs to keep track of them and it needs to be added to the UI). But does these voter account have to be verified too ? Just like any other notification tied to a membership (hence the verified controller account), it notified members of publicly available data but it could potentially give a convenient way to track other people too.

- [ ] Account actions that you are watching get sent to my email

**Comment by dmtrjsg** [comment]
Multiple account adding controls examples: 
- https://www.figma.com/file/YBfvoRpnduOXxUnA9kvNP5/Ninja-Pioneer-Design?node-id=38%3A78740&t=6VQQuyVBmeqnxwzm-0

**Comment by KubaMikolajczyk** [comment]
Design work for this is done ✅ and ready to be reviewed in figma:
- Allow email notifications when registering first membership - [Link](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-design?node-id=11859%3A445222&t=TmT2GlYncv01eE6v-4)
- Allow email notifications when registering new another membership - [Link](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-design?node-id=11859%3A445225&t=TmT2GlYncv01eE6v-4)
- Notification management in settings/ notifications tab - [Link](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-design?node-id=11859%3A445228&t=TmT2GlYncv01eE6v-4)
- Notify exisitng members about new email notifications - [Link](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-design?node-id=11856%3A445078&t=TmT2GlYncv01eE6v-4)
- User set “watch” on proposals - [Link](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-design?node-id=11860%3A489688&t=TmT2GlYncv01eE6v-4)
- User set “watch” on working groups - [Link](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-design?node-id=11860%3A489691&t=TmT2GlYncv01eE6v-4)
- User set “watch” on forum categories -[ Link](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-design?node-id=11860%3A489694&t=TmT2GlYncv01eE6v-4)
- User set “watch” on forum threads - [Link](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-design?node-id=11860%3A489697&t=TmT2GlYncv01eE6v-4)

**Comment by KubaMikolajczyk** [comment]
All of the feedback and comments requested by @dmtrjsg are implemented ✅
https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-design?node-id=11859%3A445228&t=fnJSkV1lbIysdXSc-4

**Comment by dmtrjsg** [comment]
@KubaMikolajczyk and another case in addition to figma>

1. We need a user story for cases when the BE auth token expires and user needs to re-sign up. This can to be prompted  with the same modal that we use for existing members, but with additional copy that BE Auth token expired. 

2. This option would also need to be available from the settings menu as user may choose not to re-sign up upon seeing that modal right away.

**Comment by dmtrjsg** [comment]
## Final Designs
[Link to Figma > ](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-design?node-id=11947%3A504163&t=3gi7rhvnyH2LhA64-1)
