### ISSUE TITLE
Validators Dev Epic

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4321]
## Context
- #3819
- #4105

## Designs

🆕 [Link to Figma Designs > ](https://www.figma.com/file/QnjZuWYtGimTEkQlN6MNlH/Validators?type=design&node-id=100-48288&mode=design&t=nWRhVkKaUSy1Vu7k-0)

### Validators:
- https://github.com/Joystream/pioneer/issues/4326
- https://github.com/Joystream/pioneer/issues/4330 🆕 
- https://github.com/Joystream/pioneer/issues/4334
- https://github.com/Joystream/pioneer/issues/4327 🆕 
- https://github.com/Joystream/pioneer/issues/4328 🆕 
- https://github.com/Joystream/pioneer/issues/4329 🆕 
- https://github.com/Joystream/joystream/issues/4823
- https://github.com/Joystream/joystream/issues/4824
- #4487
- [ ] #4595 🆕 
- [x] #4677

### Nominators:
- [x] #4596 
- [x] #4597
- [x] #4598
- [x] #4599
- [x] #4600
- [x] #4601
- [ ] #4602

V2.0 ⛔  OUT OF SCOPE FOR V1 
- https://github.com/Joystream/pioneer/issues/4331
- https://github.com/Joystream/pioneer/issues/4332
- https://github.com/Joystream/pioneer/issues/4333
- [ ] Validator dashboard - Validator Performance Chart
- [ ] Slashed Validators Tab
- [ ] Validator Module Notifications
- [ ] Delegate Tokens
- [ ] Validator Claim Rewards
- [ ] Nominator Claim Rewards

**Comment by traumschule** [comment]
Added comment [here](https://github.com/Joystream/pioneer/issues/4326#issuecomment-1535028960)

**Comment by dmtrjsg** [comment]
⚠️ How to calculate individual Nominator and Validator Rewards:

Shared Validator Set Rewards - THIS ONE DONE BY CHAIN IN THE END OF EACH ERA
In each era, a function of
− totalIssuance.at(lastBlockOfEra)
− erasTotalStake(era)
- erasRewardPoints(era).total
=  validatorSetRewardInEra

Individual Rewards for each Validator, before split between (vals + noms)
In each era, equal to:
(validatorSetRewardInEra × erasRewardPoints(era).stashOfVal / 
erasRewardPoints(era).total)
- slashedInEra(era,stashOfVal)
= totalValidatorRewardInEra


Individual Rewards for each Validators (vals + noms)
In each era, equal to:

valCommission = totalValidatorRewardInEra(era) × commission% / 100
sharedReward = totalValidatorRewardInEra(era) − totalValidatorRewardInEra(era) × commission% / 100
= totalValidatorRewardInEra(era) × (1 00 − commission%)


valReward(era) = valCommission + sharedReward × valOwnStake(era) / totalValStake(era)

nomReward_i(era) = sharedReward × nomStake_i(era) / totalValStake(era)

**Comment by traumschule** [comment]
Also see [reward calculation](https://github.com/Joystream/substrate/blob/master/frame/staking/README.md#reward-calculation)

**Comment by eshark9312** [comment]
- According to the design, there's a `Select`/`Nominated` button in the validator item, is the disabled `Nominated` button only displayed after `Nominate` flow? Is this for the nominator account which is just set?
- The design for `Edit` nominator account flow is missed.
 
![edit button](https://github.com/Joystream/pioneer/assets/129978066/73dceb60-d8ac-435f-8416-d60ce5255ebc)

**Comment by dmtrjsg** [comment]
1. Yes it is disabled when a given validator is shortlisted.  One member can have multiple nominator accounts and can stake for same validators. 
2. It just opens the modal with the bonding preferences (same as create)
3. Correct, the list of nominators can show any nominator accounts provided by member and their stash account
4. Correct, I think it is there as a placeholder and when less amount is selected it shows validation error.
