### ISSUE TITLE
Forum thread & proposal labeling

### ISSUE THREAD

**Issue by chrlschwb** [Joystream/pioneer#4498]
- [ ] [Label Metaprotocol in Forum Thread and Proposals #4830](https://github.com/Joystream/joystream/issues/4830)
- [ ] [Create and assign labels #4831](https://github.com/Joystream/joystream/issues/4831)
- [ ] Functionality for adding/editing/hiding/unhiding labels
- [ ] Showing labels on forum threads and proposals
- [ ] Search function for labels
