### ISSUE TITLE
Upgrade to Olympia tracking issue

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#498]
# Intro

A tracking issue related to the integration with the Olympia version of the Joystream.

### Changes from the initial implementation

*   Handling of images in Pioneer - The initial design assumed that the user would provide URI for the image. The Olympia version assumes that media is stored by the Joystream itself using IPFS.

### TODO

*   [ ] Avatar images in the storage system (#54)
*   [ ] Member by handle has a dedicated search query (#499)
*   [ ] Hydra 2.x does not yet support filtering (#500)
*   [x] Check types of the string-like metadata in transactions (#501)
*   [x] Membership entry (#765)

**Comment by jodator** [comment]
The issue & the milestone are bit outdated. A new effort will be done to review the Pioneer implementation #1475
