### ISSUE TITLE
Connect to Olympia testnet

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#743]
### Requirements

*   [x] Upgrade schema & types #767
*   [x] Allow switching networks (local/testnet) #771
*   [x] Connect to the Olympia testnet #771
*   [x] Align code to the real-world data #784 

#### Tech details:

*   WS endpoint: wss:_//olympia-dev.joystream.app/rpc_
*   Query-node graphql server endpoint: [https:_//olympia-dev.joystream.app/query/server/graphql_](https://olympia-dev.joystream.app/query/server/graphql)
*   Indexer graphql endpoint: [https:_//olympia-dev.joystream.app/query/gateway/graphql_](https://olympia-dev.joystream.app/query/gateway/graphql)
